import mongoose from "mongoose";
import { env } from "../config/env.js";
import { RuntimeSetting } from "../models/RuntimeSetting.js";

export type RuntimeSettingType = "boolean" | "number" | "secret" | "string" | "url";

export type RuntimeSettingDefinition = {
  key: string;
  label: string;
  category: string;
  type: RuntimeSettingType;
  envValue: string;
  impact: string;
  runtimePriority: boolean;
  requiresRestart?: boolean;
};

export const runtimeSettingDefinitions: RuntimeSettingDefinition[] = [
  setting(
    "BACKEND_PUBLIC_URL",
    "Backend public URL",
    "Platform URLs",
    "url",
    env.BACKEND_PUBLIC_URL,
    "Changes public API links generated by the backend. Use a real public backend URL in production.",
    true,
  ),
  setting(
    "FRONTEND_PUBLIC_URL",
    "Frontend public URL",
    "Platform URLs",
    "url",
    env.FRONTEND_PUBLIC_URL,
    "Changes customer-facing links in emails, tracking URLs, and redirects generated by the backend.",
    true,
  ),
  setting(
    "NEXT_PUBLIC_API_BASE_URL",
    "Frontend API base URL",
    "Platform URLs",
    "url",
    process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:4000/api/v1",
    "Used by the frontend build/runtime to call APIs. Changing it in admin stores the value, but a frontend restart/redeploy may be needed.",
    false,
    true,
  ),
  setting(
    "LOG_LEVEL",
    "Log level",
    "Platform",
    "string",
    env.LOG_LEVEL,
    "Controls backend logging verbosity. Lower levels are noisier and useful during debugging.",
    false,
    true,
  ),
  setting(
    "JWT_ACCESS_TTL_SECONDS",
    "JWT access TTL seconds",
    "Security",
    "number",
    String(env.JWT_ACCESS_TTL_SECONDS),
    "Controls how long admin/customer access tokens stay valid. Shorter is safer but users re-authenticate more often.",
    false,
    true,
  ),
  setting(
    "JWT_REFRESH_TTL_DAYS",
    "JWT refresh TTL days",
    "Security",
    "number",
    String(env.JWT_REFRESH_TTL_DAYS),
    "Controls how long refresh sessions can continue. Longer is more convenient but increases risk if tokens leak.",
    false,
    true,
  ),
  setting(
    "ADMIN_TOTP_REQUIRED",
    "Admin TOTP required",
    "Security",
    "boolean",
    String(env.ADMIN_TOTP_REQUIRED),
    "Controls whether admin login requires authenticator 2FA. Disabling reduces security and should only be temporary.",
    false,
    true,
  ),
  setting(
    "TOTP_ISSUER",
    "TOTP issuer",
    "Security",
    "string",
    env.TOTP_ISSUER,
    "Name shown inside authenticator apps for admin 2FA setup.",
    false,
    true,
  ),
  setting(
    "CLOUDINARY_CLOUD_NAME",
    "Cloudinary cloud name",
    "Media",
    "string",
    env.CLOUDINARY_CLOUD_NAME ?? "",
    "Cloudinary account used for media uploads. Wrong value breaks uploads and image delivery.",
    false,
    true,
  ),
  setting(
    "CLOUDINARY_API_KEY",
    "Cloudinary API key",
    "Media",
    "secret",
    env.CLOUDINARY_API_KEY ?? "",
    "Cloudinary API credential for uploads. Treat as secret.",
    false,
    true,
  ),
  setting(
    "CLOUDINARY_API_SECRET",
    "Cloudinary API secret",
    "Media",
    "secret",
    env.CLOUDINARY_API_SECRET ?? "",
    "Cloudinary secret for uploads/signing. Treat as highly sensitive.",
    false,
    true,
  ),
  setting(
    "MERCHANDISING_NEW_ARRIVAL_DAYS",
    "New arrival days",
    "Merchandising",
    "number",
    String(env.MERCHANDISING_NEW_ARRIVAL_DAYS),
    "Products newer than this many days can receive the New Arrival badge.",
    false,
    true,
  ),
  setting(
    "MERCHANDISING_BEST_SELLER_UNITS",
    "Best seller units",
    "Merchandising",
    "number",
    String(env.MERCHANDISING_BEST_SELLER_UNITS),
    "Sales unit threshold for automatic Best Seller badges.",
    false,
    true,
  ),
  setting(
    "MERCHANDISING_TRENDING_SCORE",
    "Trending score",
    "Merchandising",
    "number",
    String(env.MERCHANDISING_TRENDING_SCORE),
    "Popularity score threshold for automatic Trending badges.",
    false,
    true,
  ),
  setting(
    "MERCHANDISING_BADGE_JOB_INTERVAL_MINUTES",
    "Badge job interval minutes",
    "Merchandising",
    "number",
    String(env.MERCHANDISING_BADGE_JOB_INTERVAL_MINUTES),
    "How often automatic merchandising badges recompute. Lower values increase background work.",
    false,
    true,
  ),
  setting(
    "CART_GIFT_PACKAGING_FEE",
    "Gift packaging fee",
    "Cart",
    "number",
    String(env.CART_GIFT_PACKAGING_FEE),
    "Amount charged when customers enable gift packaging. Applies immediately in cart.",
    true,
  ),
  setting(
    "ABANDONED_CART_THRESHOLD_MINUTES",
    "Abandoned cart threshold minutes",
    "Cart",
    "number",
    String(env.ABANDONED_CART_THRESHOLD_MINUTES),
    "Cart inactivity duration before abandoned cart events are generated.",
    true,
  ),
  setting(
    "ABANDONED_CART_JOB_INTERVAL_MINUTES",
    "Abandoned cart job interval minutes",
    "Cart",
    "number",
    String(env.ABANDONED_CART_JOB_INTERVAL_MINUTES),
    "How often the abandoned cart job runs. Existing running timers may need restart.",
    false,
    true,
  ),
  setting(
    "WISHLIST_SIGNAL_JOB_INTERVAL_MINUTES",
    "Wishlist signal job interval minutes",
    "Wishlist",
    "number",
    String(env.WISHLIST_SIGNAL_JOB_INTERVAL_MINUTES),
    "How often wishlist price/stock signals refresh. Existing running timers may need restart.",
    false,
    true,
  ),
  setting(
    "RAZORPAY_KEY_ID",
    "Razorpay key ID",
    "Payments",
    "secret",
    env.RAZORPAY_KEY_ID ?? "",
    "Razorpay public key identifier. Wrong value breaks gateway payments.",
    false,
    true,
  ),
  setting(
    "RAZORPAY_KEY_SECRET",
    "Razorpay key secret",
    "Payments",
    "secret",
    env.RAZORPAY_KEY_SECRET ?? "",
    "Razorpay secret used for gateway calls/signatures. Treat as highly sensitive.",
    false,
    true,
  ),
  setting(
    "RAZORPAY_WEBHOOK_SECRET",
    "Razorpay webhook secret",
    "Payments",
    "secret",
    env.RAZORPAY_WEBHOOK_SECRET ?? "",
    "Used to verify Razorpay webhook authenticity. Wrong value rejects webhooks.",
    false,
    true,
  ),
  setting(
    "RAZORPAY_ENABLE_GATEWAY_CALLS",
    "Enable Razorpay gateway calls",
    "Payments",
    "boolean",
    String(env.RAZORPAY_ENABLE_GATEWAY_CALLS),
    "When false, Razorpay calls are stubbed for development. Production should use true with valid credentials.",
    false,
    true,
  ),
  setting(
    "COD_MANUAL_REVIEW_THRESHOLD",
    "COD manual review threshold",
    "Payments",
    "number",
    String(env.COD_MANUAL_REVIEW_THRESHOLD),
    "COD orders at or above this amount are flagged for manual review. Applies immediately.",
    true,
  ),
  setting(
    "UPI_PAYMENT_ADDRESS",
    "UPI payment address",
    "Payments",
    "string",
    env.UPI_PAYMENT_ADDRESS,
    "Fallback UPI ID used if payment settings are not configured in admin payments.",
    true,
  ),
  setting(
    "UPI_QR_IMAGE_URL",
    "UPI QR image URL",
    "Payments",
    "url",
    env.UPI_QR_IMAGE_URL,
    "Fallback QR image shown if admin payment settings do not provide one.",
    true,
  ),
  setting(
    "BANK_ACCOUNT_NAME",
    "Bank account name",
    "Payments",
    "string",
    env.BANK_ACCOUNT_NAME,
    "Fallback bank account name for manual bank transfers.",
    true,
  ),
  setting(
    "BANK_ACCOUNT_NUMBER",
    "Bank account number",
    "Payments",
    "string",
    env.BANK_ACCOUNT_NUMBER,
    "Fallback bank account number for manual bank transfers.",
    true,
  ),
  setting(
    "BANK_IFSC",
    "Bank IFSC",
    "Payments",
    "string",
    env.BANK_IFSC,
    "Fallback IFSC code for manual bank transfers.",
    true,
  ),
  setting(
    "BANK_NAME",
    "Bank name",
    "Payments",
    "string",
    env.BANK_NAME,
    "Fallback bank name for manual bank transfers.",
    true,
  ),
  setting(
    "MANUAL_PAYMENT_INSTRUCTIONS",
    "Manual payment instructions",
    "Payments",
    "string",
    env.MANUAL_PAYMENT_INSTRUCTIONS,
    "Fallback instructions shown for manual payment methods.",
    true,
  ),
  setting(
    "SMTP_HOST",
    "SMTP host",
    "Email",
    "string",
    env.SMTP_HOST,
    "SMTP server host used to send booking confirmation emails.",
    true,
  ),
  setting(
    "SMTP_PORT",
    "SMTP port",
    "Email",
    "number",
    String(env.SMTP_PORT),
    "SMTP server port. Usually 465 for secure SMTP.",
    true,
  ),
  setting(
    "SMTP_SECURE",
    "SMTP secure",
    "Email",
    "boolean",
    String(env.SMTP_SECURE),
    "When true, backend connects with TLS from the start. Use with port 465.",
    true,
  ),
  setting(
    "SMTP_USER",
    "SMTP username",
    "Email",
    "secret",
    env.SMTP_USER,
    "SMTP login username. Treat as secret.",
    true,
  ),
  setting(
    "SMTP_PASS",
    "SMTP password",
    "Email",
    "secret",
    env.SMTP_PASS,
    "SMTP login password/app password. Treat as highly sensitive.",
    true,
  ),
  setting(
    "SMTP_FROM_EMAIL",
    "SMTP from email",
    "Email",
    "string",
    env.SMTP_FROM_EMAIL,
    "Sender email address for booking emails. If blank, email sending is skipped.",
    true,
  ),
  setting(
    "SMTP_FROM_NAME",
    "SMTP from name",
    "Email",
    "string",
    env.SMTP_FROM_NAME,
    "Sender display name shown in customer emails.",
    true,
  ),
  setting(
    "SHIPPING_STANDARD_FEE",
    "Standard shipping fee",
    "Shipping",
    "number",
    String(env.SHIPPING_STANDARD_FEE),
    "Shipping charge for standard delivery below free-shipping threshold. Applies immediately.",
    true,
  ),
  setting(
    "SHIPPING_EXPRESS_FEE",
    "Express shipping fee",
    "Shipping",
    "number",
    String(env.SHIPPING_EXPRESS_FEE),
    "Shipping charge for express delivery. Applies immediately.",
    true,
  ),
  setting(
    "SHIPPING_FREE_THRESHOLD",
    "Free shipping threshold",
    "Shipping",
    "number",
    String(env.SHIPPING_FREE_THRESHOLD),
    "Cart subtotal required for free standard shipping. Applies immediately.",
    true,
  ),
];

export async function listRuntimeSettings() {
  const overrides = await getOverrides();

  return runtimeSettingDefinitions.map((definition) => {
    const override = overrides.get(definition.key);

    return {
      ...definition,
      effectiveValue: override ?? definition.envValue,
      hasOverride: override !== undefined,
      overrideValue: override ?? "",
    };
  });
}

export async function saveRuntimeSettings(values: Record<string, string>, updatedBy?: string) {
  const allowed = new Set(runtimeSettingDefinitions.map((item) => item.key));
  const operations = Object.entries(values)
    .filter(([key]) => allowed.has(key))
    .map(([key, value]) => {
      const normalizedValue = String(value ?? "").trim();

      if (!normalizedValue) {
        return { deleteOne: { filter: { key } } };
      }

      return {
        updateOne: {
          filter: { key },
          update: { $set: { key, updatedBy, value: normalizedValue } },
          upsert: true,
        },
      };
    });

  if (operations.length) {
    await RuntimeSetting.bulkWrite(operations);
  }

  return listRuntimeSettings();
}

export async function getRuntimeSetting(key: string) {
  const definition = runtimeSettingDefinitions.find((item) => item.key === key);

  if (!definition) {
    return undefined;
  }

  const override = await getOverride(key);
  return override ?? definition.envValue;
}

export async function getRuntimeNumberSetting(key: string, fallback: number) {
  const value = await getRuntimeSetting(key);
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

export async function getRuntimeBooleanSetting(key: string, fallback: boolean) {
  const value = await getRuntimeSetting(key);

  if (value === undefined || value === "") {
    return fallback;
  }

  return value === "true";
}

async function getOverride(key: string) {
  if (mongoose.connection.readyState === 0) {
    return undefined;
  }

  const setting = (await RuntimeSetting.findOne({ key }).lean()) as { value?: string } | null;
  return setting?.value;
}

async function getOverrides() {
  if (mongoose.connection.readyState === 0) {
    return new Map<string, string>();
  }

  const settings = (await RuntimeSetting.find({}).lean()) as unknown as Array<{
    key: string;
    value: string;
  }>;
  return new Map(settings.map((item) => [item.key, item.value]));
}

function setting(
  key: string,
  label: string,
  category: string,
  type: RuntimeSettingType,
  envValue: string,
  impact: string,
  runtimePriority: boolean,
  requiresRestart = false,
): RuntimeSettingDefinition {
  return { category, envValue, impact, key, label, requiresRestart, runtimePriority, type };
}
